language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "TjIi7sOTDi3/BWG4h79a/ojBaafda9iIaHunaDkC2yVjHqlgCe4mlyWjzwXBrnS7fwI/q6CMqv9FzDlrk51ygpIwNnEzWdsO9++4cxNX0BSizEstzZz7uTTRQAA0BRkFgsfbFKS88ktkJrFM8dabDWgTfpTd/l1fVxgDOPIbxUidYn5gtBE5kEFdF7zv5j9JhIwtf+CUYfJarSlTFid8Cgesx9o3HgH4xeqlh2Wm1ONjsLSRgwkWGomNyyzbp0IZlxSDvyWgIfiXW6MSVIEVk6Yf3sT+cRlwU9qNpsqJppLZ8NPKGKKckltvsdjUX7kyKguyweBUawYqz4gkAQ7VRMqKphgkz4Mrsg/O63qeKts3klHGM4v5FJ5Fn1pxGlQ/Lso2vExYsSrL9TXNEyh5oCIuYTl4HPFYr9d0Dn/fUlrWAS2yIIwUAQlqYP2LqTUchCX3OsowhmNxP/i1aW9+xGIGu+bdtE3lo0ogEuJgMKRDHm+meguT63PxcpiJ6ETmX+aYRUGUufFk3V+rm52oe3L2Ys6BuCjzvYWH8BqC+dbSF3BlZAXDd9itdlKXTbPdEPO7/VhGQDosBM037wC2Gge9YLhDc+2Zvp/TjwoHPYkmuXcG9pZ1ozze+5qXSMJ48ELiQsTi4TpbjksmH7QOH/o/2d1IESypWPf1Dky80P8="
